getty-zig/getty

.github/workflows/ci.yml, .github/workflows/docs.yml, src/de.zig, src/de/concepts/deserializer.zig, src/de/error.zig, src/de/impls/visitor/buf_map.zig, src/de/impls/visitor/slice.zig, src/de/interfaces/deserializer.zig, src/de/interfaces/visitor.zig
Three main changes in this PR:
1. `getty.Deserializer` implementations must now always include `getty.de.Error` in their error set.
1. Visitors now return `error.Unsupported` instead of raising a compile error.
1. `getty.Deserializer` now has a `deserializeAny` method, enabling deserializers of self-describing formats to deserialize solely based off of their input.
Closes #21.
=> Add `deserializeAny` method to `getty.Deserializer`

src/attributes.zig, src/de/impls/visitor/hash_map.zig, src/de/impls/visitor/struct.zig, src/de/impls/visitor/tail_queue.zig, src/de/impls/visitor/tuple.zig, src/de/impls/visitor/union.zig, src/ser/blocks/struct.zig
The struct info in the standard library was updated with a 'field' field.
=> ser, de: Replace field_type with type

src/de/traits/attributes.zig, src/ser/traits/attributes.zig
has_attributes was incorrectly checking only TSBs and TDBs.
=> ser, de: Check SBTs and DBTs for attributes

src/de.zig, src/de/blocks/packed_int_array.zig, src/de/impls/visitor/packed_int_array.zig, src/ser.zig, src/ser/blocks/packed_int.zig
Support for `std.PackedIntArray` was added for both serialization and deserialization.
However, support for `std.PackedIntSlice` was only added to serialization. I don't think there's a way to make them directly. As an alternative, one can just deserialize into a `std.PackedIntArray` first and then slice into a `std.PackedIntSlice`.
=> Add support for std.PackedIntArray and std.PackedIntSlice

src/de.zig, src/getty.zig, src/ser.zig
This fixes the documentation for both interfaces in the API reference.
=> ser, de: Move Serializer and Deserializer to getty.zig

src/de/impls/visitor/array.zig
The string is not part of the final value, so the caller should always deallocate it, if it is indeed allocated.
=> de: Do not free string during array deserialization

src/de.zig
=> de: Remove enum branch for type-defined blocks

src/de/blocks/array.zig, src/de/blocks/array_list.zig, src/de/blocks/bool.zig, src/de/blocks/buf_map.zig, src/de/blocks/enum.zig, src/de/blocks/float.zig, src/de/blocks/int.zig, src/de/blocks/linked_list.zig, src/de/blocks/net_address.zig, src/de/blocks/optional.zig, src/de/blocks/packed_int_array.zig, src/de/blocks/pointer.zig, src/de/blocks/slice.zig, src/de/blocks/struct.zig, src/de/blocks/tail_queue.zig, src/de/blocks/tuple.zig, src/de/blocks/union.zig, src/de/blocks/void.zig, src/testing/de.zig
One pointer (string) tests have been moved/added to the pointer block. Some of those tests were incorrectly in the slice block.
=> de: Test deserialize instead of getty.deserialize

src/ser/blocks/struct.zig
If an empty attribute list was specified, struct serialization would end up incorrect as the length of the struct would always be 0.
=> ser: Fix struct length when attributes are defined

src/ser/blocks/allocator.zig, src/ser/blocks/array.zig, src/ser/blocks/array_list.zig, src/ser/blocks/bool.zig, src/ser/blocks/bounded_array.zig, src/ser/blocks/buf_map.zig, src/ser/blocks/enum.zig, src/ser/blocks/error.zig, src/ser/blocks/float.zig, src/ser/blocks/hash_map.zig, src/ser/blocks/int.zig, src/ser/blocks/linked_list.zig, src/ser/blocks/multi_array_list.zig, src/ser/blocks/net_address.zig, src/ser/blocks/null.zig, src/ser/blocks/optional.zig, src/ser/blocks/packed_int.zig, src/ser/blocks/pointer.zig, src/ser/blocks/slice.zig, src/ser/blocks/string.zig, src/ser/blocks/struct.zig, src/ser/blocks/tail_queue.zig, src/ser/blocks/tuple.zig, src/ser/blocks/union.zig, src/ser/blocks/vector.zig, src/ser/blocks/void.zig, src/ser/serialize.zig, src/ser/testing.zig
This allows the serialize function in SBs to allocate if necessary. For example, serializing SemanticVersion values as strings requires allocation since they can be arbitrarily long.
=> ser: Take an optional allocator in SBs

src/de/impls/visitor/enum.zig, src/de/impls/visitor/struct.zig, src/de/impls/visitor/tuple.zig, src/de/impls/visitor/union.zig
Setting the quota based on the number of fields didn't work out. The formula I used was `1000 + (fields.len * 2) + (fields.len * fields.len)`. That got me close to the actual quota I needed but there was some extra branches that I couldn't account for. So, I decided instead to do away with the half-working solution and just set a nice large arbitrary quota.
Considering how #103 only needs 1,708 branches, the quota of 10,000 seems reasonable to me.
Closes #103.
=> de: Set evaluation branch quota

build.zig
Apparently Zig now has a default clean step.
=> build: Remove clean step

src/de/tuples.zig
It's broken for aarch64 now too ;-;. Zig why
=> de: Temporarily disable std.net.Address support

examples/bool-deserializer/main.zig, examples/build.zig, examples/seq-deserializer/main.zig
1. Update `build.zig` to ensure it can be compiled successfully under Zig 0.11.
2. Update to the latest version of the JSON API.
=> Make examples run again

src/de/blocks.zig, src/de/blocks/buf_set.zig, src/de/blocks/segmented_list.zig, src/de/blocks/semantic_version.zig, src/de/blocks/uri.zig, src/de/impls/visitor/buf_set.zig, src/de/impls/visitor/segmented_list.zig, src/de/impls/visitor/semantic_version.zig, src/de/impls/visitor/uri.zig, src/de/tuples.zig, src/ser/blocks.zig, src/ser/blocks/buf_set.zig, src/ser/blocks/segmented_list.zig, src/ser/blocks/uri.zig, src/ser/tuples.zig
Context: https://github.com/getty-zig/getty/issues/120
Added (de)serialization support for the following standard library types:
- BufSet
- Uri
- SegementedList
=> ser, de: Add support for more standard library types

build.zig
- `Compile.emit_X` fields has been replaced by `Compile.getEmittedX()` functions in https://github.com/ziglang/zig/commit/5c0181841081170a118d8e50af2a09f5006f59e1, artifacts now default to not being emitted
- `Compile.setMainPkgPath` has been removed with `main_pkg_path` now being an option as part of https://github.com/ziglang/zig/commit/38840e2e586d71f2b38ed825ea02529f615c5f0c
=> chore: update build.zig to new std.Build API

src/de/blocks.zig, src/de/blocks/enum_multiset.zig, src/de/blocks/indexed_array.zig, src/de/blocks/indexed_map.zig, src/de/blocks/indexed_set.zig, src/de/blocks/linear_fifo.zig, src/de/blocks/priority_dequeue.zig, src/de/blocks/priority_queue.zig, src/de/error.zig, src/de/impls/visitor/array.zig, src/de/impls/visitor/enum_multiset.zig, src/de/impls/visitor/indexed_array.zig, src/de/impls/visitor/indexed_map.zig, src/de/impls/visitor/indexed_set.zig, src/de/impls/visitor/linear_fifo.zig, src/de/impls/visitor/priority_dequeue.zig, src/de/impls/visitor/priority_queue.zig, src/de/tuples.zig, src/ser/blocks.zig, src/ser/blocks/enum_multiset.zig, src/ser/blocks/indexed_array.zig, src/ser/blocks/indexed_map.zig, src/ser/blocks/indexed_set.zig, src/ser/blocks/linear_fifo.zig, src/ser/blocks/priority_dequeue.zig, src/ser/blocks/priority_queue.zig, src/ser/tuples.zig
Context: https://github.com/getty-zig/getty/issues/120
Added (de)serialization support for the following standard library types:
cc: @ibokuri for review
=> ser, de: Add support for more standard library types #2

src/de/interfaces/map_access.zig, src/de/interfaces/seq_access.zig, src/de/interfaces/variant_access.zig
This commit implements proposal https://github.com/getty-zig/getty/issues/127 to adds allocation check functions
for aggregate access interfaces, namingly the functions `isElementAllocated`,
`isValueAllocated`, `isPayloadAllocated` to the SeqAccess, MapAccess and
VariantAccess interfaces respectively. This allows checking the storage
location of a value deserialized from access methods (e.g., `nextKey`) and
makes it possible to conditionally free the value only if it is allocated on
the heap. Thus, eliminating the need to unconditionally free values which
in some cases force an allocator to be passed for deserialization even if
no allocation would take place, contravening the principle of least privilege.
closes https://github.com/getty-zig/getty/issues/127
=> de: Add allocation check functions to aggregate access interfaces

src/de/interfaces/deserializer.zig, src/de/interfaces/map_access.zig, src/de/interfaces/seed.zig, src/de/interfaces/seq_access.zig, src/de/interfaces/union_access.zig, src/de/interfaces/variant_access.zig, src/de/interfaces/visitor.zig
Before this PR, `getty.de.MapAccess`'s documentation looked like this:
After this PR, its documentation looks like this:
And if you click on one of the method types, you are sent to the source code where you can clearly see the full signature of the method.
Also, notice the difference between `nextKeySeed`'s type and `nextKey`'s types in the second screenshot. The former is not prefixed with a `?`. While all interface methods are technically optional (for reasons irrelevant to this PR), some methods are "provided" by Getty for the user's convenience (i.e., they have a default implementation that is used if the user doesn't provide one).
Provided methods are now prefixed with a `?` to indicate their optionality, while "required" methods do not display the leading `?` in order to indicate …
=> de: Better autodocs for interface methods

src/de/blocks/slice.zig, src/de/de.zig, src/de/impls/deserializer/content.zig, src/de/impls/visitor/array.zig, src/de/impls/visitor/content.zig, src/de/impls/visitor/enum.zig, src/de/impls/visitor/ignored.zig, src/de/impls/visitor/net_address.zig, src/de/impls/visitor/pointer.zig, src/de/impls/visitor/semantic_version.zig, src/de/impls/visitor/slice.zig, src/de/impls/visitor/uri.zig, src/de/interfaces/visitor.zig, src/de/lifetime.zig, src/de/testing.zig, src/ser/testing.zig, src/testing.zig
Next up is updating visitString's return type and then updating the return type of the access methods.
I want to get this merged in first though to see if there are any performance improvements with slices now being used directly if they're Heap values.
=> Introduce lifetime parameter to visitString

src/de/de.zig, src/de/impls/deserializer/content.zig, src/de/impls/visitor/array.zig, src/de/impls/visitor/content.zig, src/de/impls/visitor/enum.zig, src/de/impls/visitor/ignored.zig, src/de/impls/visitor/net_address.zig, src/de/impls/visitor/pointer.zig, src/de/impls/visitor/semantic_version.zig, src/de/impls/visitor/slice.zig, src/de/impls/visitor/uri.zig, src/de/interfaces/visitor.zig, src/de/testing.zig
This'll allow deserializers to know whether or not the value passed to `visitString` was used. If so, then it should not be freed unless the managing entity wants to free it.
=> Update visitString return type to include used Boolean

src/de/deserialize.zig, src/de/impls/deserializer/content.zig, src/de/impls/seed/default.zig, src/de/impls/seed/ignored.zig, src/de/interfaces/seed.zig, src/de/testing.zig
this should prevent any nesting of the result arena allocator.
=> remove Result from Seed's return type

src/attributes.zig, src/ser/serialize.zig
error: redundant inline keyword in comptime scope
=> fix compiler errors on 0.12.0-dev.1828+225fe6ddb

build.zig, build.zig.zon, src/de_test.zig, src/ser_test.zig
This updates the project to be compatible with the new build system changes.
The additional `ser_test.zig` and `de_test.zig` files are required as changing a module's root path is no longer supported.
=> build: update to new Build API

build.zig.zon
Rewrites the `protest` dependency url in `build.zig.zon` (doesn't change the dependency version). Fixes the following error seen on latest Zig master (`0.12.0-dev.2811+3cafb9655`):
```sh
getty/build.zig.zon:13:20: error: unable to unpack git files: BadZlibHeader
.url = "git+https://github.com/ibokuri/protest.git#bae398b701e763ef18480aa3cfcca103716996de",
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
---
To reproduce the error:
1. Add the latest Zig to your PATH
2. Clear Zig caches (to ensure Zig build will attempt to fetch the `protest` dependency instead of using a cached version; there might be a better way to do this that doesn't involve nuking the entire cache): `rm -rf ~/.cache/zig; cd path/to/getty; rm -rf zig-cache zig-out`
3. Run `zig …
=> deps: Update ibokuri dependency url

build.zig, build.zig.zon
Updates build.zig due to changes in LazyPath.
Note: Before merging this PR, we need to update build.zig.zon after (https://github.com/ibokuri/protest/pull/1) is merged.
=> Update to Zig 0.13.0-dev.249+ed75f6256
